[package]
name = "project-publisher"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["blocking"] }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
path = "src/lib.rs"
